# Generated by Django 5.0.3 on 2024-07-24 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField(null=True)),
                ("gender", models.IntegerField(null=True)),
                ("height", models.IntegerField(null=True)),
                ("ap_hi", models.IntegerField(null=True)),
                ("ap_lo", models.IntegerField(null=True)),
                ("cholesterol", models.IntegerField(null=True)),
                ("glucose", models.IntegerField(null=True)),
                ("alco", models.IntegerField(null=True)),
                ("active", models.IntegerField(null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
            ],
        ),
    ]
