# Generated by Django 5.0.3 on 2024-07-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_patientdata_createdat_patientdata_prediction"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdata",
            name="smoke",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="patientdata",
            name="weight",
            field=models.IntegerField(null=True),
        ),
    ]
