# Generated by Django 5.0.3 on 2024-07-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_patientdata_smoke_patientdata_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdata",
            name="bp_encoded",
            field=models.IntegerField(null=True),
        ),
    ]
