# Generated by Django 5.0.3 on 2024-07-24 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_patientdata_bp_encoded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientdata",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
        ),
    ]
