# Generated by Django 5.0.3 on 2024-07-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_patientdata_prediction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientdata",
            name="createdAt",
            field=models.DateField(null=True),
        ),
    ]
