# Generated by Django 5.0.3 on 2024-08-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_patientdata_createdat"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdata",
            name="leading_cause_1",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patientdata",
            name="leading_cause_2",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patientdata",
            name="leading_cause_3",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
